Add tests and raport coverage
ministero-salute/it-dgc-verificaC19-android pull request #45
Opened 2021-06-14 17:21 UTC by android-developer-123

2021-06-16 13:24 UTC, astagi requested changes

2021-06-16 13:24 UTC, astagi commented on app/src/test/java/it/ministerodellasalute/verificaC19/TimeExtTest.kt
> -
@android-developer-123 is it possible to make it pass instead of deleting it?

2021-06-17 13:50 UTC, Light2288 commented
@astagi i tried to add back the test but unfortunately it is based on a conversion to local date, so it depends on time zone on the machine where the build is run
On my local machine the test is passing correctly
Maybe it is better to remove it, otherwise i will think about a way to refactor it, if you have any suggestion please let me know
Thank you.

2021-06-17 17:44 UTC, astagi commented
> @astagi i tried to add back the test but unfortunately it is based on a conversion to local date, so it depends on time zone on the machine where the build is run
> On my local machine the test is passing correctly
> I tried a couple of fixes but it seems to fail in any case, the expected time on your machine is 11:03 while on my local machine the test passes with 13:03
> Maybe it is better to remove it, otherwise i will think about a way to refactor it, if you have any suggestion please let me know
> Thank you.

@Light2288 I tried to force timezone in gradlew script and it works https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/46 WDYT? Better setting it before launching the command?

2021-06-18 11:17 UTC, Light2288 commented
> > @astagi i tried to add back the test but unfortunately it is based on a conversion to local date, so it depends on time zone on the machine where the build is run
> > On my local machine the test is passing correctly
> > I tried a couple of fixes but it seems to fail in any case, the expected time on your machine is 11:03 while on my local machine the test passes with 13:03
> > Maybe it is better to remove it, otherwise i will think about a way to refactor it, if you have any suggestion please let me know
> > Thank you.
> 
> @Light2288 I tried to force timezone in gradlew script and it works #46 WDYT? Better setting it before launching the command?

I was thinking if there was some alternative in order to not change this gradle (even if I don't think it has other impacts) , but the conversion to LocalDate made all my tied fixes to fail
I approved #46, i will keep you updated if I find some way to implement everything test side
Thank you

2021-06-18 11:47 UTC, astagi commented
> > > @astagi i tried to add back the test but unfortunately it is based on a conversion to local date, so it depends on time zone on the machine where the build is run
> > > On my local machine the test is passing correctly
> > > I tried a couple of fixes but it seems to fail in any case, the expected time on your machine is 11:03 while on my local machine the test passes with 13:03
> > > Maybe it is better to remove it, otherwise i will think about a way to refactor it, if you have any suggestion please let me know
> > > Thank you.
> > 
> > 
> > @Light2288 I tried to force timezone in gradlew script and it works #46 WDYT? Better setting it before launching the command?
> 
> I was thinking if there was some alternative in order to not change this gradle (even if I don't think it has other impacts) , but the conversion to LocalDate made all my tied fixes to fail
> I approved #46, i will keep you updated if I find some way to implement everything test side
> Thank you

Sure! Thank you!

2021-06-18 11:55 UTC, astagi approved these changes

2021-06-18 11:56 UTC, merged